import type { Clinic } from "./clinics";

export const mockClinics: Clinic[] = [
  {
    id: "mock-1",
    name: "Community Health Center of Midtown",
    address: "100 Main St",
    lat: 40.7527,
    lng: -73.9772,
    distanceMi: 0.8,
    type: "community-health",
    typeLabel: "Community health",
    isHrsa: true,
  },
  {
    id: "mock-2",
    name: "University School of Dentistry",
    address: "421 1st Ave",
    lat: 40.7408,
    lng: -73.9757,
    distanceMi: 2.1,
    type: "dental-school",
    typeLabel: "Dental school",
  },
  {
    id: "mock-3",
    name: "Free Dental Days — Local Nonprofit",
    address: "250 Broadway",
    lat: 40.7131,
    lng: -74.0072,
    distanceMi: 3.4,
    type: "free",
    typeLabel: "Free clinic",
  },
  {
    id: "mock-4",
    name: "County Public Health Dental",
    address: "90 Church St",
    lat: 40.7135,
    lng: -74.0094,
    distanceMi: 4.0,
    type: "community-health",
    typeLabel: "Community health",
    isHrsa: true,
  },
  {
    id: "mock-5",
    name: "Oral Medicine Specialty Clinic",
    address: "635 W 165th St",
    lat: 40.8406,
    lng: -73.9423,
    distanceMi: 5.2,
    type: "dental-school",
    typeLabel: "Dental school",
  },
];
