#!/usr/bin/env python3
"""
One-shot runner: use our already-downloaded GA CSV data to run the
map-post pipeline (generate map → Claude caption → Telegram → Publora).
Skips the live GA API call since the service account key isn't present.
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
os.chdir(os.path.dirname(__file__))

from oralcheck_agent import (
    generate_map_caption,
    tg_drain_updates,
    tg_send_media,
    tg_send_text,
    tg_poll_command,
    tg_poll_freetext,
    publora_post,
    log,
)

# GA data from the exported CSV (Demographic_details_Country.csv)
COUNTRY_DATA = {
    "United States": 131,
    "India":    2,
    "Ireland":  2,
    "Italy":    2,
    "Sweden":   2,
    "Belgium":  1,
    "Canada":   1,
    "China":    1,
    "Estonia":  1,
    "Germany":  1,
    "Spain":    1,
    "Taiwan":   1,
    "Ukraine":  1,
}

DRY_RUN = "--dry-run" in sys.argv

# Use the animated reel (generated by Manim via oralcheck_reel.py)
map_path    = "/Users/ianharris/Desktop/oralcheck_reel.mp4"
media_kind  = "reel"
n_countries = len(COUNTRY_DATA)
total_users = sum(COUNTRY_DATA.values())
log.info("Using animated reel: %s (%d countries, %d users)", map_path, n_countries, total_users)

log.info("Generating caption with Claude...")
content = generate_map_caption(COUNTRY_DATA, n_countries, total_users)
content["hashtags"] = content.get("hashtags", [])[:5]   # hard cap at 5
log.info("Hook: %s", content["hook"])

next_offset = tg_drain_updates()

preview_text = (
    f"MAP POST\n\n"
    f"HOOK\n{content['hook']}\n\n"
    f"CAPTION\n{content['caption']}\n\n"
    f"HASHTAGS\n{' '.join('#' + h for h in content.get('hashtags', []))}\n\n"
    f"DATA: {n_countries} countries · {total_users:,} users\n\n"
    f"Commands:\n  APPROVE — post to Instagram\n  REJECT  — give feedback\n  SKIP    — discard"
)

log.info("Sending preview to Telegram...")
last_msg_id = tg_send_media(preview_text, map_path, media_kind)
log.info("Waiting for your reply (APPROVE / REJECT / SKIP)...")

reply = tg_poll_command(last_msg_id, start_offset=next_offset)

if reply == "APPROVE":
    if DRY_RUN:
        tg_send_text("Dry run — no post created.")
        log.info("DRY RUN — done.")
    else:
        log.info("Approved. Posting to Instagram...")
        result = publora_post(
            content["caption"],
            content.get("hashtags", []),
            [map_path],
            media_kind,
        )
        post_id = result.get("postGroupId", "unknown")
        tg_send_text(f"Map post published. Post ID: {post_id}")
        log.info("Done. Post ID: %s", post_id)

elif reply == "REJECT":
    next_offset2 = tg_drain_updates()
    ask_id = tg_send_text("What should I change? Reply with your feedback.")
    feedback = tg_poll_freetext(ask_id, start_offset=next_offset2)
    if feedback:
        log.info("Feedback: %s", feedback)
        tg_send_text(f"Got it. Re-run the script to regenerate with: {feedback}")
    else:
        tg_send_text("No feedback received. Re-run to try again.")

elif reply == "SKIP":
    tg_send_text("Skipped. Nothing posted.")
    log.info("Skipped.")

else:
    tg_send_text("Timed out. Nothing posted.")
    log.info("Timed out.")
